= webdriverfactory
:toc:

>can go back to https://github.com/kazurayam/webdriverfactory

webdriverfactory is a Java/Groovy library that wraps `org.openqa.selenium.webdriver.chrome.ChromeDriver`.
It enables you to launch Chrome browser while specifying a "User Profile", for example "Picasso". And also you can lauch Chrome browser while specifying a "Profile Directory Name", for example "Default" or "Profile 1".

You have an option where to find the profile directory:


== Examples

=== Launch Chrome browser without profile specified

Basic case where we launch Chrome browser without profile specified. The example includes how to launch Headless brower. Also includes how to position and resize the browser window.

[source, groovy]
----
include::../src/test/groovy/examples/LaunchChromeWithoutProfile.groovy[]
----

=== Launch Chrome browser with UserProfile specified

[source, groovy]
----
include::../src/test/groovy/examples/LaunchChromeWithUserProfile.groovy[]
----


=== Launch Headless Chrome with ProfileDirectoryName specified

[source, groovy]
----
include::../src/test/groovy/examples/LaunchChromeWithProfileDirectory.groovy[]
----

=== Launch Multiple Chrome windows in Tiling layout

[source, groovy]
----
include::../src/test/groovy/examples/LaunchMultipleChromeWindowsInTilingLayout.groovy[]
----

=== Launch Multiple Chrome windows in Stacking layout

[source, groovy]
----
include::../src/test/groovy/examples/LaunchMultipleChromeWindowsInStackingLayout.groovy[]
----

=== print the DesiredCapabilities employed to open a Chrome

[source, groovy]
----
include::../src/test/groovy/examples/PrintEmployedDesiredCapabilities.groovy[]
----

This emits:
----
{
    "acceptSslCerts": true,
    "browserName": "chrome",
    "goog:chromeOptions": {
        "args": [
            "window-size=1024,768",
            "--no-sandbox",
            "disable-infobars",
            "disable-gpu",
            "disable-dev-shm-usage",
            "--incognito"
        ],
        "extensions": [

        ],
        "prefs": {
            "plugins.plugins_disabled": [
                "Adobe Flash Player",
                "Chrome PDF Viewer"
            ],
            "profile.default_content_settings.popups": 0,
            "download.prompt_for_download": false,
            "download.default_directory": "/Users/kazuakiurayama/Downloads"
        }
    }
}
----

=== print UserProfile, ProfieDirectoryName, UserDataDir used to launche a Chrome

[source, groovy]
----
include::../src/test/groovy/examples/PrintWebDriverMetadata.groovy[]
----

This emits
----
ChromeUserProfile : {
    "userProfile": "Kazurayam",
    "profileDirectoryName": "Default",
    "userDataDir": "/Users/kazurayam/Library/Application Support/Google/Chrome"
}
UserDataAccess: TO_GO
----

== What is "user profile", "user-data-dir" and "profile directory" in Chrome

What is "user profile" in Chrome browser? There are a few articles about it, for example

* https://www.guidingtech.com/things-about-google-chrome-profiles/

== Problem to solve

== Solution

== Description

1. `UserDataAccess.FOR_HERE` : ChromeDriverFactory tries to find the profile directory in the Chrome's genuine "user-data-dir". On Mac, it is `/Users/myosusername/Library/Application Support/Google/Chrome/`. A process of Chrome browser demands to lock the genuine profile directory. While a Chrome process is already running, when you try to open another Chrome with FOR_HERE option, the new comer process will fail.
2. `UserDataAccess.TO_GO` : ChromeDriverFactory allocates a new temporary directory and in there will create a profile directory. Then ChromeDriverFactory will copy the content of the genuine profile directory into the temporary directory. When you open Chrome with TO_GO option the process will run. However, all of session data saved into this temporary profile directory will be discarded (cookies, cached page resources, etc) when you close the session.
