= ChromeDriverFactory
:toc:

>can go back to https://github.com/kazurayam/chromedriverfactory

chromedriverfactory is a Java/Groovy library that wraps `org.openqa.selenium.webdriver.chrome.ChromeDriver`.
It enables you to launch Chrome browser while specifying a "User Profile", for example "Picasso". And also you can launch Chrome browser while specifying a "Profile Directory Name", for example "Default" or "Profile 1".

== Sample codes

=== Launch Chrome browser without profile specified

Basic case where we launch Chrome browser without profile specified. The example includes how to launch Headless browser. Also includes how to position and resize the browser window.

[source, groovy]
----
include::../src/test/groovy/examples/LaunchChromeWithoutProfile.groovy[]
----

=== Launch Chrome browser with UserProfile specified

[source, groovy]
----
include::../src/test/groovy/examples/LaunchChromeWithUserProfile.groovy[]
----


=== Launch Headless Chrome with ProfileDirectoryName specified

[source, groovy]
----
include::../src/test/groovy/examples/LaunchChromeWithProfileDirectory.groovy[]
----

=== print the DesiredCapabilities employed to open a Chrome

[source, groovy]
----
include::../src/test/groovy/examples/PrintEmployedOptions.groovy[]
----

This emits:
----
{
    "acceptSslCerts": true,
    "browserName": "chrome",
    "goog:chromeOptions": {
        "args": [
            "window-size=1024,768",
            "--no-sandbox",
            "disable-infobars",
            "disable-gpu",
            "disable-dev-shm-usage",
            "--incognito"
        ],
        "extensions": [

        ],
        "prefs": {
            "plugins.plugins_disabled": [
                "Adobe Flash Player",
                "Chrome PDF Viewer"
            ],
            "profile.default_content_settings.popups": 0,
            "download.prompt_for_download": false,
            "download.default_directory": "/Users/kazuakiurayama/Downloads"
        }
    }
}
----

=== print UserProfile, ProfieDirectoryName, UserDataDir used to launche a Chrome

[source, groovy]
----
include::../src/test/groovy/examples/PrintWebDriverMetadata.groovy[]
----

This emits
----
ChromeUserProfile : {
    "userProfile": "kazurayam",
    "userDataDir": "/var/folders/lh/jkh513dn7f3c0j09z131g1z00000gn/T/__user-data-dir__7144377108201112266",
    "profileDirectoryName": "Default"
}
UserDataAccess: TO_GO
----


== Problem to solve

A quotation from https://chromedriver.chromium.org/capabilities

____
By default, ChromeDriver will create a new temporary profile for each session. At times you may want to set special preferences or just use a custom profile altogether. If the former, you can use the 'chrome.prefs' capability (described later below) to specify preferences that will be applied after Chrome starts. If the latter, you can use the user-data-dir Chrome command-line switch to tell Chrome which profile to use:
____





=== What is "user profile", "user-data-dir" and "profile directory" in Chrome

What is "user profile" in Chrome browser? There are a few articles about it, for example

* https://www.guidingtech.com/things-about-google-chrome-profiles/

== Solution

== Description

You have an option where to find the profile directory:

1. `UserDataAccess.FOR_HERE` : ChromeDriverFactory tries to find the profile directory in the Chrome's genuine "user-data-dir". On Mac, it is `/Users/myosusername/Library/Application Support/Google/Chrome/`. A process of Chrome browser demands to lock the genuine profile directory. While a Chrome process is already running, when you try to open another Chrome with FOR_HERE option, the new comer process will fail.
2. `UserDataAccess.TO_GO` : ChromeDriverFactory allocates a new temporary directory and in there will create a profile directory. Then ChromeDriverFactory will copy the content of the genuine profile directory into the temporary directory. When you open Chrome with TO_GO option the process will run. However, all of session data saved into this temporary profile directory will be discarded (cookies, cached page resources, etc) when you close the session.


https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies[Using HTTP Cookies, MDN Web Docs]